workflows:
  ios-app-workflow:
    name: iOS App Workflow
    max_build_duration: 60
    instance_type: mac_mini

    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      - name: Install MobSFScan
        script: |
          pip3 install --upgrade mobsfscan
      - name: Run MobSFScan
        script: |
          mobsfscan --json --type ios -o mobsfscan_result.json .
      - name: Upload MobSFScan results
        script: |
          mkdir -p artifacts
          mv mobsfscan_result.json artifacts/
    artifacts:
      - artifacts/mobsfscan_result.json


